id: d224bc22131d4cae9e3605db6234b0f1
initial_creation_type: ocr
source_metadata:
  volumes:
    c646e143e09e4b10adfe7ad7023372cd:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
